name: basebuild

on:
  pull_request:
    branches: [main]
  push:
    tags:
      - "v*"
    branches: [main]

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  goreleaser:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: true

      # The prebuilt golangci-lint doesn't support go 1.18+ yet
      # https://github.com/golangci/golangci-lint/issues/2649
      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3

      # - name: Run tests
      #   run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
